In [1]:
from pathlib import Path
import pandas as pd
import sys
PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0,str(PROJECT_ROOT),)
risk_metrics = pd.read_csv(
    PROJECT_ROOT
    / "reports"
    / "risk_metrics.csv"
)

stress_results = pd.read_csv(
    PROJECT_ROOT
    / "reports"
    / "stress_results.csv"
)

daily_pnl = pd.read_csv(
    PROJECT_ROOT
    / "reports"
    / "daily_pnl.csv"
)

In [2]:
var_99 = float(
    risk_metrics.loc[
        risk_metrics["metric"]
        == "Historical VaR 99%",
        "value",
    ].iloc[0]
)

es_99 = float(
    risk_metrics.loc[
        risk_metrics["metric"]
        == "Expected Shortfall 99%",
        "value",
    ].iloc[0]
)

daily_loss = daily_pnl[
    "daily_pnl"
].min()

stress_loss = stress_results[
    "stress_pnl"
].min()

In [3]:
from src.risk.limit_monitor import (
    evaluate_risk_limits,
)

limit_results = evaluate_risk_limits(
    var_99=var_99,
    expected_shortfall_99=es_99,
    daily_loss=daily_loss,
    stress_loss=stress_loss,
)

limit_results

                  metric          value  warning_limit  breach_limit   status
0                 var_99   92151.254906          75000        100000  WARNING
1  expected_shortfall_99  139652.442336         110000        150000  WARNING
2             daily_loss -284663.695095        -100000       -150000   BREACH
3            stress_loss -434787.922852        -200000       -300000   BREACH

In [4]:
limit_results.to_csv(
    PROJECT_ROOT
    / "reports"
    / "risk_limit_results.csv",
    index=False,
)

In [5]:
breaches = limit_results[
    limit_results["status"]
    == "BREACH"
]

warnings = limit_results[
    limit_results["status"]
    == "WARNING"
]

print("BREACHES")
display(breaches)

print("WARNINGS")
display(warnings)

BREACHES

        metric          value  warning_limit  breach_limit  status
2   daily_loss -284663.695095        -100000       -150000  BREACH
3  stress_loss -434787.922852        -200000       -300000  BREACH

WARNINGS

                  metric          value  warning_limit  breach_limit   status
0                 var_99   92151.254906          75000        100000  WARNING
1  expected_shortfall_99  139652.442336         110000        150000  WARNING